### ISSUE TITLE
Protobuf version problem

### ISSUE THREAD

**Issue by suheylkiris** [Qengineering/Paddle-Jetson-Nano#2]
Hello.
I try to install paddlepaddle_gpu on Jetson Xaiver Nx. When i try to follow guide pip3 installation on this link https://qengineering.eu/install-paddle-on-jetson-nano.html everthing looks fine. But protobuf version getting error like ##  protobuf requires Python '>=3.7' but the running Python is 3.6.9. I install protobuf 3.19.4 which compatible with python 3.6.9 everything looks like OK. But when i execute  "sudo -H pip3 install paddlepaddle_gpu-2.0.0-cp36-cp36m-linux_aarch64.whl" command, i am getting error about protobuf version. Probably it occurs cause in requirements.txt file has just protobuf not protobuf==3.19.4. Is there any other PADDLE_GPU version compatible with python 3.7 or newer version or could you update requirements file with python 3.6 supported versions.

**Comment by Qengineering** [comment]
I'm sorry, at the moment there is no other version available. 
The Jetson Nano has ships with Python 3.6. If you upgrade with the Ubuntu 20.04 version, you get Python 3.7.
With the new protobuf is force users to install the Ubuntu 20.04. However, I [can't install all requirements under 20.04](https://stackoverflow.com/questions/75272737/error-invalid-version-0-23ubuntu1-package-distro-info). 
It will take time to solve this issue. Being very busy, it will take a while.

**Comment by suheylkiris** [comment]
I figured out my problem. I installed paddlepaddle_gpu on my Jetson Xavier Nx with Python 3.7. I download cp37 version from this link: 
https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html#python

Then i applied pip3 steps from this link: 
https://qengineering.eu/install-paddle-on-jetson-nano.html

hints:
use virtualenv,

after "pip3 install paddleocr" step versions should be like

numpy==1.23.5
protobuf==3.22.0
onnx=1.11.0

**Comment by Qengineering** [comment]
Glad you could solve it!
Thanks for the info.
